# uncompyle6 version 3.9.0
# Python bytecode version base 2.7 (62211)
# Decompiled from: Python 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)]
# Embedded file name: C:\TeamCity\buildAgent\work\dc8eb0b1d2cf198a\Main\client\standalone\build\pyi.win32\run_obfuscated\out00-PYZ.pyz\shared.constants_shop
SHOP_URL = '127.0.0.1:8000'
SHOP_CONNECTION_TIMEOUT = 5.0
SHOP_MANAGER_LIST_REQUEST, SHOP_MANAGER_PURCHASE_REQUEST, SHOP_MANAGER_PURCHASE_FINALIZE = xrange(3)
SHOP_MANAGER_FINALIZE, SHOP_MANAGER_CANCEL = xrange(2)
SHOP_RETURN_SUCCESS = 1
SHOP_RETURN_FAILED = 2
SHOP_RETURN_INVALID_PARAMETER = 3
SHOP_RETURN_INTERNAL_ERROR = 4
SHOP_RETURN_USER_HAS_NOT_APPROVED_TRANSACTION = 5
SHOP_RETURN_TRANSACTION_ALREADY_COMMITTED = 6
SHOP_RETURN_USER_NOT_LOGGED_IN = 7
SHOP_RETURN_CURRENCY_DOES_NOT_MATCH_USERS = 8
SHOP_RETURN_ACCOUNT_DOESNT_EXIST = 9
SHOP_RETURN_USER_DENIED_TRANSACTION = 10
SHOP_RETURN_TRANSACTION_DENIED_USER_IN_RESTRICTED_COUNTRY = 11
SHOP_RETURN_INSUFFICIENT_FUNDS = 100
SHOP_RETURN_TIME_LIMIT_TO_FINALIZE_EXCEEEDED = 101
SHOP_RETURN_ACCOUNT_DISABLED = 102
SHOP_RETURN_ACCOUNT_NOT_ALLOWED_TO_PURCHASE = 103
SHOP_RETURN_TRANSACTION_DENIED_FRAUD_DETECTION = 104
SHOP_RETURN_NO_ITEMS_SENT_OR_ALREADY_OWN_THEM = 200
SHOP_RETURN_TRANSACTION_ALREADY_REFUNDED = 201
SHOP_CATEGORY_INVALID, SHOP_CATEGORY_ALL, SHOP_CATEGORY_TOPSELLERS, SHOP_CATEGORY_SALE, SHOP_CATEGORY_NEW, SHOP_CATEGORY_MODES, SHOP_CATEGORY_EQUIPMENT, SHOP_CATEGORY_PACKS, SHOP_CATEGORY_MAPS = xrange(9)
SHOPITEM_INVALID, SHOPITEM_MAFIA_PACK = xrange(2)
ITEM_LIST = {SHOPITEM_MAFIA_PACK: [
                       'unlock_ctf']}
DLC_AppID01 = 1
DLC_AppName01 = 'Ace of Spades DLC Pack #1'
DLC_AppID02 = 420650
DLC_AppName02 = 'Ace of Spades DLC Pack #2'
DLC_APPID_LIST = {DLC_AppName02: DLC_AppID02}
# okay decompiling out\shared.constants_shop.pyc
